version: '1.3'
services:
  # mysql数据库构建
  adminmysql:
    image: mysql:8.0
    volumes:
      - C:\Users\R\Desktop\docker-compose\dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    hostname: adminmysql

  # 后端接口构建
  adminservice:
    build: ./admin_server
    ports:
      - 8082:8082

  # 前端web构建
  adminweb:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - D:/campusAccessControl_server/admin/dist:/usr/share/nginx/html
